# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - openemm

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_80cbaaf7bbe541c2a84b823ac9b863bd }}
        password: ${{ secrets.AzureAppService_ContainerPassword_00f40bc5d34d48829703a4c00188cc66 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_80cbaaf7bbe541c2a84b823ac9b863bd }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'openemm'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f78603f593814fcd9b34e2c7906b38b9 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_80cbaaf7bbe541c2a84b823ac9b863bd }}/appsvc/staticsite:${{ github.sha }}'